# Generated by Django 3.2.5 on 2021-07-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorbackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorbackend',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='vendorbackend',
            name='rating',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorbackend',
            name='vendor_id',
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
    ]
